function(check_cli expected_code expected_output)
    execute_process(COMMAND "${CLI}" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT "${code}" STREQUAL "${expected_code}")
        message(FATAL_ERROR "Unexpected status ${code}: ${error}")
    endif()
    if(NOT "${output}" MATCHES "${expected_output}")
        message(FATAL_ERROR "Unexpected output: ${output}")
    endif()
endfunction()
execute_process(COMMAND "${CLI}" --version
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT "${code}" STREQUAL "0" OR NOT "${output}" STREQUAL "sqlicon ${VERSION}\n" OR NOT "${error}" STREQUAL "")
    message(FATAL_ERROR "Version must match CMake: code=${code}, stdout=${output}, stderr=${error}")
endif()
check_cli(0 "sqlicon ${VERSION}" -V)
check_cli(0 "--version" --help)
check_cli(0 "[Ss]yntax error" --finderr -201)
check_cli(3 "^$" --finderr not-a-number)
check_cli(3 "^$" --finderr -2147483648)
check_cli(3 "^$" --version --profile-delete must-not-be-touched --yes)
check_cli(3 "^$" --profile-show must-not-be-touched --password ignored)
check_cli(3 "^$" --profile-create must-not-be-touched --connect-uri "informix+onsocssl://host:9088/db")
file(READ "${MANPAGE}" manual)
string(FIND "${manual}" "sqlicon ${VERSION}" version_position)
if(version_position LESS 0)
    message(FATAL_ERROR "Manpage version does not match CMake")
endif()
