#include "unity.h"

/* Phase 1 tests */
void test_sqli_create_destroy(void);
void test_sqli_create_null_out_ptr(void);
void test_sqli_destroy_null(void);
void test_sqli_create_multiple(void);
void test_sqli_destroy_closes_socket(void);
void test_sqli_error_null_safe(void);
void test_sqli_errno_no_error(void);
void test_sqli_error_info_no_error(void);
void test_sqli_strict_protocol_toggle(void);
void test_sqli_trim_trailing_spaces_toggle(void);
void test_sqli_query_with_retry_null_params(void);
void test_sqli_pad_even_zero(void);
void test_sqli_pad_even_even(void);
void test_sqli_pad_even_odd(void);
void test_sqli_pad_even_large(void);

/* Phase 2 tests */
void test_sl_header_encode_conreq(void);
void test_sl_header_encode_conacc(void);
void test_sl_header_encode_redirect(void);
void test_sl_header_decode_too_small(void);
void test_sl_header_decode_null(void);
void test_sl_header_encode_null_buf(void);
void test_asc_string_encode_hello(void);
void test_asc_string_encode_empty(void);
void test_asc_string_encode_null(void);
void test_asc_string_encode_overflow(void);
void test_asc_encode_padded_odd(void);
void test_asc_encode_padded_even_with_pad(void);
void test_asc_encode_padded_null(void);
void test_ipc_preamble_base64_is_padded(void);
void test_ipc_preamble_dynamic_magic(void);
void test_sl_encode_conreq(void);
void test_sl_encode_null_buf(void);
void test_sl_encode_too_small(void);

/* Phase 3 tests */
void test_dispatch_describe_zero_columns(void);
void test_dispatch_multi_row_result(void);
void test_dispatch_done_exposes_generated_serial(void);
void test_dispatch_insertdone_exposes_generated_serial8(void);
void test_dispatch_error_response(void);
void test_dispatch_error_response_sets_error_info(void);
void test_dispatch_error_response_drains_truncated_string(void);
void test_get_bytes_fetchblob_roundtrip(void);
void test_dispatch_unknown_opcode_sets_diagnostics(void);
void test_dispatch_unknown_opcode_strict_mode_fails(void);
void test_error_classify_network_retryable_sqlcode(void);
void test_error_classify_auth_not_retryable(void);
void test_error_classify_protocol_unknown_opcode_not_retryable(void);
void test_error_classify_generic_transport_message_retryable(void);
void test_retry_recommend_network_backoff(void);
void test_retry_recommend_nonretryable_auth(void);
void test_query_with_retry_retries_on_retryable_error(void);
void test_query_with_retry_nonreadonly_does_not_retry(void);
void test_query_select_closes_once_and_destroy_sends_nothing(void);
void test_send_eot(void);
void test_send_command_sql(void);
void test_send_command_null(void);
void test_send_fetch_bool_does_not_send_ret_type(void);
void test_send_fetch_varchar_sends_ret_type(void);
void test_send_open_forward_cursor(void);
void test_send_open_scroll_hold_cursor(void);
void test_send_scroll_fetch_varchar_sends_sfetch(void);
void test_result_destroy_null(void);
void test_result_columns_null(void);
void test_result_rows_null(void);
void test_result_next_null(void);
void test_result_scroll_navigation(void);
void test_result_first_scroll_refetches_with_sfetch_absolute(void);
void test_result_get_string_cp1252_to_utf8_iconv(void);
void test_result_destroy_skips_close_when_stmt_invalid(void);

/* Phase 4 tests */
void test_encode_decode_date_epoch(void);
void test_encode_decode_date_positive(void);
void test_encode_decode_date_negative(void);
void test_encode_decode_datetime_full(void);
void test_encode_decode_datetime_exact_year(void);
void test_encode_decode_datetime_time_only(void);
void test_encode_decode_datetime_null_ptrs(void);
void test_encode_decode_datetime_boundaries(void);
void test_encode_decimal_positive(void);
void test_encode_decimal_negative(void);
void test_encode_decimal_null_buf(void);
void test_encode_decimal_too_small_buf(void);
void test_encode_decimal_invalid_precision(void);
void test_encode_decode_decimal_roundtrip(void);
void test_decode_decimal_with_precision(void);
void test_extract_int_from_tuple(void);
void test_extract_bigint_from_tuple(void);
void test_extract_float_from_tuple(void);
void test_extract_varchar_from_tuple(void);
void test_extract_varchar_null_result(void);
void test_column_name_out_of_range(void);
void test_column_type_out_of_range(void);
void test_prepare_null_params(void);
void test_prepare_with_retry_null_params(void);
void test_prepare_with_retry_retries_on_retryable_error(void);
void test_bind_null_stmt(void);
void test_execute_null_stmt(void);
void test_execute_rejects_unimplemented_prepared_lob_streaming(void);
void test_execute_with_retry_null_stmt(void);
void test_execute_with_retry_retries_on_retryable_error(void);
void test_execute_with_retry_nonreadonly_does_not_retry(void);
void test_stmt_close_null(void);
void test_stmt_destroy_null(void);
void test_stmt_next_null_result(void);
void test_stmt_result_null(void);
void test_result_get_int_null(void);
void test_result_get_int64_null(void);
void test_result_get_double_null(void);
void test_result_get_string_null(void);
void test_result_get_bytes_null(void);
void test_result_get_int_from_mock_result(void);
void test_result_get_string_from_mock_result(void);
void test_result_next_recomputes_packed_offsets(void);
void test_dt_001_varchar_roundtrip_ascii(void);
void test_dt_002_varchar_roundtrip_utf8(void);
void test_dt_003_char_padding_trim(void);
void test_dt_004_char_padding_preserve_when_trim_disabled(void);
void test_dt_005_empty_string_vs_no_row(void);
void test_dt_009_lvarchar_roundtrip(void);
void test_dt_010_lvarchar_marker_len8_roundtrip(void);
void test_dt_101_smallint_bounds(void);
void test_dt_102_integer_bounds(void);
void test_dt_103_bigint_bounds(void);
void test_dt_104_serial8_bounds(void);
void test_dt_201_decimal_roundtrip_precision_scale(void);
void test_dt_201_decimal_get_double_packed(void);
void test_dt_202_numeric_get_double_packed(void);
void test_dt_203_money_get_double_packed(void);
void test_dt_204_decimal_get_string_and_null(void);
void test_dt_206_result_is_null_and_was_null(void);
void test_dt_301_float_double_roundtrip(void);
void test_dt_401_date_roundtrip(void);
void test_dt_402_date_string_epoch_mapping(void);
void test_dt_501_boolean_roundtrip(void);
void test_dt_611_stream_bytes_chunked(void);
void test_dt_412_datetime_semantic_object(void);
void test_dt_413_interval_semantic_object(void);
void test_dt_414_datetime_interval_two_column_layout(void);
void test_dt_timestamp_retrieval(void);
void test_sqli_epoch_helpers(void);


void test_stability_decimal_codec_loop(void);
void test_stability_bind_api_reuse(void);
void test_call_prepare_null_params(void);
void test_call_prepare_not_ready_conn(void);
void test_call_api_null_safe(void);

/* Phase 4b — prepared statement coverage */
void test_bind_int_success(void);
void test_bind_int64_success(void);
void test_bind_double_success(void);
void test_bind_timestamp_success(void);
void test_bind_epoch_success(void);


void test_bind_int_invalid_index(void);
void test_bind_int64_invalid_index(void);
void test_bind_double_invalid_index(void);
void test_bind_null_int_success(void);
void test_bind_null_int64_success(void);
void test_bind_null_double_success(void);
void test_bind_null_int_invalid_index(void);
void test_bind_null_int64_invalid_index(void);
void test_bind_null_double_invalid_index(void);
void test_bind_null_invalid_index(void);
void test_bind_string_invalid_index(void);
void test_bind_date_invalid_index(void);
void test_bind_datetime_invalid_index(void);
void test_bind_interval_invalid_index(void);
void test_bind_bool_invalid_index(void);
void test_bind_decimal_invalid_index(void);
void test_bind_bytes_invalid_index(void);
void test_bind_bytes_null_value(void);
void test_bind_bytes_zero_len(void);
void test_bind_bytes_success(void);
void test_bind_string_null_value(void);
void test_bind_date_null_value(void);
void test_bind_bool_true_false(void);
void test_bind_string_rebind(void);
void test_bind_bytes_rebind(void);
void test_stmt_zero_params_close_destroy(void);
void test_stmt_next_not_executed(void);
void test_stmt_result_not_valid(void);
void test_result_column_name_valid(void);
void test_result_column_name_null_result(void);
void test_result_column_name_negative_index(void);
void test_result_column_name_out_of_bounds(void);
void test_result_column_type_valid(void);
void test_result_column_type_null_result(void);
void test_result_column_type_negative_index(void);
void test_result_column_type_out_of_bounds(void);
void test_stmt_close_sends_control_msgs(void);
void test_stmt_close_invalid_stmt_id(void);
void test_lob_streaming_null_stmt(void);
void test_lob_streaming_null_param_server_types(void);
void test_lob_streaming_null_param(void);
void test_execute_no_params_sends_id_and_exec(void);
void test_execute_with_retry_nonreadonly_skip(void);
void test_execute_with_params_int(void);
void test_execute_with_params_int64(void);
void test_execute_with_params_double(void);
void test_execute_with_params_string(void);
void test_execute_with_params_null(void);
void test_execute_with_params_bytes(void);
void test_execute_with_params_date(void);
void test_execute_with_params_decimal(void);
void test_execute_with_params_multiple(void);
void test_bind_decimal_success(void);
void test_bind_decimal_negative(void);
void test_bind_datetime_success(void);
void test_bind_interval_success(void);
void test_prepare_execute_null_stmt(void);
void test_prepare_execute_with_retry_null_stmt(void);
void test_prepare_execute_with_retry_null_conn(void);
void test_prepare_stmt_next_null_stmt(void);
void test_prepare_stmt_result_null_stmt(void);
void test_result_column_name_zero_count(void);
void test_result_column_type_zero_count(void);

/* Phase 5 tests — transactions */
void test_begin_null_conn(void);
void test_begin_not_ready_conn(void);
void test_begin_already_in_transaction(void);
void test_begin_socket_not_connected(void);
void test_commit_null_conn(void);
void test_commit_no_active_transaction(void);
void test_rollback_null_conn(void);
void test_rollback_no_active_transaction(void);
void test_autocommit_null_conn(void);
void test_autocommit_default(void);
void test_autocommit_off_with_active_txn(void);
void test_isolation_null_conn(void);
void test_isolation_default(void);
void test_isolation_set_get(void);
void test_isolation_invalid(void);
void test_isolation_in_transaction(void);
void test_in_transaction_null(void);
void test_in_transaction_state(void);
void test_batch_begin_null_conn(void);
void test_batch_end_null_conn(void);
void test_batch_in_state_null(void);
void test_batch_begin_end_sends_opcodes(void);
void test_batch_begin_twice_invalid(void);
void test_batch_end_without_begin_invalid(void);
void test_batch_execute_null_params(void);
void test_batch_execute_not_ready_conn(void);
void test_batch_result_accessors_null_safe(void);
void test_savepoint_set_writes_opcode_payload_and_flag(void);
void test_savepoint_release_and_rollback_write_expected_opcodes(void);
void test_savepoint_rejected_in_autocommit(void);

/* Phase 5 tests — sqlhosts */
void test_parse_null_output(void);
void test_parse_nonexistent_file(void);
void test_parse_env_sqlhosts(void);
void test_parse_and_find(void);
void test_parse_with_empty_lines_and_comments(void);
void test_find_null_entries(void);
void test_find_nonexistent_server(void);
void test_find_null_server_name(void);
void test_find_count_zero(void);

/* Phase 7 tests — URI connection */
void test_uri_null_conn(void);
void test_uri_null_uri(void);
void test_uri_empty_uri(void);
void test_uri_bad_syntax(void);
void test_uri_unsupported_scheme(void);
void test_uri_missing_server_param(void);
void test_uri_onsoctcp_missing_host(void);
void test_uri_onsoctcp_full(void);
void test_uri_onsoctcp_no_creds(void);
void test_uri_onsoctcp_explicit_creds_override(void);
void test_uri_onsoctcp_default_db(void);
void test_uri_onsoctcp_url_encoded_creds(void);
void test_uri_onsocssl_full(void);
void test_uri_onsocssl_verify_peer_off(void);
void test_uri_onipcstr_full(void);
void test_uri_onipcstr_custom_socket(void);
void test_uri_onipcstr_default_socket_priority(void);
void test_uri_client_locale(void);
void test_uri_multiple_query_params(void);
void test_uri_user_only_no_password(void);
void test_uri_explicit_user_only(void);
void test_uri_explicit_password_only(void);
void test_uri_onsoctcp_missing_port(void);

/* Phase 6 tests — integration tests */
void test_connect_success(void);
void test_connect_reject(void);
void test_connect_fragmented_conacc_body(void);
void test_connect_redirect(void);
void test_connect_bad_done(void);
void test_connect_tcp_fail(void);
void test_query_success_multi_row(void);
void test_query_success_ddl(void);
void test_query_error_response(void);
void test_query_null_params(void);
void test_txn_begin_success(void);
void test_txn_commit_success(void);
void test_txn_rollback_success(void);
void test_close_null_safe(void);
void test_close_ready_sends_exit(void);
void test_close_twice_safe(void);
void test_result_destroy_after_query(void);
void test_query_after_close(void);
void test_query_live_systables(void);
void test_pool_create_acquire_release_destroy(void);
void test_pool_acquire_timeout_when_busy(void);
void test_pool_acquire_wakes_after_release(void);
void test_pool_reconnect_after_borrower_closed_connection(void);

/* Unity hooks */
void setUp(void) {}
void tearDown(void) {}

int main(void)
{
    UNITY_BEGIN();

    /* Phase 1 */
    RUN_TEST(test_sqli_create_destroy);
    RUN_TEST(test_sqli_create_null_out_ptr);
    RUN_TEST(test_sqli_destroy_null);
    RUN_TEST(test_sqli_create_multiple);
    RUN_TEST(test_sqli_destroy_closes_socket);
    RUN_TEST(test_sqli_error_null_safe);
    RUN_TEST(test_sqli_errno_no_error);
    RUN_TEST(test_sqli_error_info_no_error);
    RUN_TEST(test_sqli_strict_protocol_toggle);
    RUN_TEST(test_sqli_trim_trailing_spaces_toggle);
    RUN_TEST(test_sqli_query_with_retry_null_params);
    RUN_TEST(test_sqli_pad_even_zero);
    RUN_TEST(test_sqli_pad_even_even);
    RUN_TEST(test_sqli_pad_even_odd);
    RUN_TEST(test_sqli_pad_even_large);

    /* Phase 2 */
    RUN_TEST(test_sl_header_encode_conreq);
    RUN_TEST(test_sl_header_encode_conacc);
    RUN_TEST(test_sl_header_encode_redirect);
    RUN_TEST(test_sl_header_decode_too_small);
    RUN_TEST(test_sl_header_decode_null);
    RUN_TEST(test_sl_header_encode_null_buf);
    RUN_TEST(test_asc_string_encode_hello);
    RUN_TEST(test_asc_string_encode_empty);
    RUN_TEST(test_asc_string_encode_null);
    RUN_TEST(test_asc_string_encode_overflow);
    RUN_TEST(test_asc_encode_padded_odd);
    RUN_TEST(test_asc_encode_padded_even_with_pad);
    RUN_TEST(test_asc_encode_padded_null);
    RUN_TEST(test_ipc_preamble_base64_is_padded);
    RUN_TEST(test_ipc_preamble_dynamic_magic);
    RUN_TEST(test_sl_encode_conreq);
    RUN_TEST(test_sl_encode_null_buf);
    RUN_TEST(test_sl_encode_too_small);

    /* Phase 3 */
    RUN_TEST(test_dispatch_describe_zero_columns);
    RUN_TEST(test_dispatch_multi_row_result);
    RUN_TEST(test_dispatch_done_exposes_generated_serial);
    RUN_TEST(test_dispatch_insertdone_exposes_generated_serial8);
    RUN_TEST(test_dispatch_error_response);
    RUN_TEST(test_dispatch_error_response_sets_error_info);
    RUN_TEST(test_dispatch_error_response_drains_truncated_string);
    RUN_TEST(test_get_bytes_fetchblob_roundtrip);
    RUN_TEST(test_dispatch_unknown_opcode_sets_diagnostics);
    RUN_TEST(test_dispatch_unknown_opcode_strict_mode_fails);
    RUN_TEST(test_error_classify_network_retryable_sqlcode);
    RUN_TEST(test_error_classify_auth_not_retryable);
    RUN_TEST(test_error_classify_protocol_unknown_opcode_not_retryable);
    RUN_TEST(test_error_classify_generic_transport_message_retryable);
    RUN_TEST(test_retry_recommend_network_backoff);
    RUN_TEST(test_retry_recommend_nonretryable_auth);
    RUN_TEST(test_query_with_retry_retries_on_retryable_error);
    RUN_TEST(test_query_with_retry_nonreadonly_does_not_retry);
    RUN_TEST(test_query_select_closes_once_and_destroy_sends_nothing);
    RUN_TEST(test_send_eot);
    RUN_TEST(test_send_command_sql);
    RUN_TEST(test_send_command_null);
    RUN_TEST(test_send_fetch_bool_does_not_send_ret_type);
    RUN_TEST(test_send_fetch_varchar_sends_ret_type);
    RUN_TEST(test_send_open_forward_cursor);
    RUN_TEST(test_send_open_scroll_hold_cursor);
    RUN_TEST(test_send_scroll_fetch_varchar_sends_sfetch);
    RUN_TEST(test_result_destroy_null);
    RUN_TEST(test_result_columns_null);
    RUN_TEST(test_result_rows_null);
    RUN_TEST(test_result_next_null);
    RUN_TEST(test_result_scroll_navigation);
    RUN_TEST(test_result_first_scroll_refetches_with_sfetch_absolute);
    RUN_TEST(test_result_get_string_cp1252_to_utf8_iconv);
    RUN_TEST(test_result_destroy_skips_close_when_stmt_invalid);

    /* Phase 4 */
    RUN_TEST(test_encode_decode_date_epoch);
    RUN_TEST(test_encode_decode_date_positive);
    RUN_TEST(test_encode_decode_date_negative);
    RUN_TEST(test_encode_decode_datetime_full);
    RUN_TEST(test_encode_decode_datetime_exact_year);
    RUN_TEST(test_encode_decode_datetime_time_only);
    RUN_TEST(test_encode_decode_datetime_null_ptrs);
    RUN_TEST(test_encode_decode_datetime_boundaries);
    RUN_TEST(test_encode_decimal_positive);
    RUN_TEST(test_encode_decimal_negative);
    RUN_TEST(test_encode_decimal_null_buf);
    RUN_TEST(test_encode_decimal_too_small_buf);
    RUN_TEST(test_encode_decode_decimal_roundtrip);
    RUN_TEST(test_decode_decimal_with_precision);
    RUN_TEST(test_extract_int_from_tuple);
    RUN_TEST(test_extract_bigint_from_tuple);
    RUN_TEST(test_extract_float_from_tuple);
    RUN_TEST(test_extract_varchar_from_tuple);
    RUN_TEST(test_extract_varchar_null_result);
    RUN_TEST(test_column_name_out_of_range);
    RUN_TEST(test_column_type_out_of_range);
    RUN_TEST(test_prepare_null_params);
    RUN_TEST(test_prepare_with_retry_null_params);
    RUN_TEST(test_prepare_with_retry_retries_on_retryable_error);
    RUN_TEST(test_bind_null_stmt);
    RUN_TEST(test_execute_null_stmt);
    RUN_TEST(test_execute_rejects_unimplemented_prepared_lob_streaming);
    RUN_TEST(test_execute_with_retry_null_stmt);
    RUN_TEST(test_execute_with_retry_retries_on_retryable_error);
    RUN_TEST(test_execute_with_retry_nonreadonly_does_not_retry);
    RUN_TEST(test_stmt_close_null);
    RUN_TEST(test_stmt_destroy_null);
    RUN_TEST(test_stmt_next_null_result);
    RUN_TEST(test_stmt_result_null);
    RUN_TEST(test_result_get_int_null);
    RUN_TEST(test_result_get_int64_null);
    RUN_TEST(test_result_get_double_null);
    RUN_TEST(test_result_get_string_null);
    RUN_TEST(test_result_get_bytes_null);
    RUN_TEST(test_result_get_int_from_mock_result);
    RUN_TEST(test_result_get_string_from_mock_result);
    RUN_TEST(test_result_next_recomputes_packed_offsets);
    RUN_TEST(test_dt_001_varchar_roundtrip_ascii);
    RUN_TEST(test_dt_002_varchar_roundtrip_utf8);
    RUN_TEST(test_dt_003_char_padding_trim);
    RUN_TEST(test_dt_004_char_padding_preserve_when_trim_disabled);
    RUN_TEST(test_dt_005_empty_string_vs_no_row);
    RUN_TEST(test_dt_009_lvarchar_roundtrip);
    RUN_TEST(test_dt_010_lvarchar_marker_len8_roundtrip);
    RUN_TEST(test_dt_101_smallint_bounds);
    RUN_TEST(test_dt_102_integer_bounds);
    RUN_TEST(test_dt_103_bigint_bounds);
    RUN_TEST(test_dt_104_serial8_bounds);
    RUN_TEST(test_dt_201_decimal_roundtrip_precision_scale);
    RUN_TEST(test_dt_201_decimal_get_double_packed);
    RUN_TEST(test_dt_202_numeric_get_double_packed);
    RUN_TEST(test_dt_203_money_get_double_packed);
    RUN_TEST(test_dt_204_decimal_get_string_and_null);
    RUN_TEST(test_dt_206_result_is_null_and_was_null);
    RUN_TEST(test_dt_301_float_double_roundtrip);
    RUN_TEST(test_dt_401_date_roundtrip);
    RUN_TEST(test_dt_402_date_string_epoch_mapping);
    RUN_TEST(test_dt_501_boolean_roundtrip);
    RUN_TEST(test_dt_611_stream_bytes_chunked);
    RUN_TEST(test_dt_412_datetime_semantic_object);
    RUN_TEST(test_dt_413_interval_semantic_object);
    RUN_TEST(test_dt_414_datetime_interval_two_column_layout);
    RUN_TEST(test_dt_timestamp_retrieval);
    RUN_TEST(test_sqli_epoch_helpers);


    RUN_TEST(test_stability_decimal_codec_loop);
    RUN_TEST(test_stability_bind_api_reuse);
    RUN_TEST(test_call_prepare_null_params);
    RUN_TEST(test_call_prepare_not_ready_conn);
    RUN_TEST(test_call_api_null_safe);

    /* Phase 4b — prepared statement coverage */
    RUN_TEST(test_bind_int_success);
    RUN_TEST(test_bind_int64_success);
    RUN_TEST(test_bind_double_success);
    RUN_TEST(test_bind_timestamp_success);
    RUN_TEST(test_bind_epoch_success);


    RUN_TEST(test_bind_int_invalid_index);
    RUN_TEST(test_bind_int64_invalid_index);
    RUN_TEST(test_bind_double_invalid_index);
    RUN_TEST(test_bind_null_int_success);
    RUN_TEST(test_bind_null_int64_success);
    RUN_TEST(test_bind_null_double_success);
    RUN_TEST(test_bind_null_int_invalid_index);
    RUN_TEST(test_bind_null_int64_invalid_index);
    RUN_TEST(test_bind_null_double_invalid_index);
    RUN_TEST(test_bind_null_invalid_index);
    RUN_TEST(test_bind_string_invalid_index);
    RUN_TEST(test_bind_date_invalid_index);
    RUN_TEST(test_bind_datetime_invalid_index);
    RUN_TEST(test_bind_interval_invalid_index);
    RUN_TEST(test_bind_bool_invalid_index);
    RUN_TEST(test_bind_decimal_invalid_index);
    RUN_TEST(test_bind_bytes_invalid_index);
    RUN_TEST(test_bind_bytes_null_value);
    RUN_TEST(test_bind_bytes_zero_len);
    RUN_TEST(test_bind_bytes_success);
    RUN_TEST(test_bind_string_null_value);
    RUN_TEST(test_bind_date_null_value);
    RUN_TEST(test_bind_bool_true_false);
    RUN_TEST(test_bind_string_rebind);
    RUN_TEST(test_bind_bytes_rebind);
    RUN_TEST(test_stmt_zero_params_close_destroy);
    RUN_TEST(test_stmt_next_not_executed);
    RUN_TEST(test_stmt_result_not_valid);
    RUN_TEST(test_result_column_name_valid);
    RUN_TEST(test_result_column_name_null_result);
    RUN_TEST(test_result_column_name_negative_index);
    RUN_TEST(test_result_column_name_out_of_bounds);
    RUN_TEST(test_result_column_type_valid);
    RUN_TEST(test_result_column_type_null_result);
    RUN_TEST(test_result_column_type_negative_index);
    RUN_TEST(test_result_column_type_out_of_bounds);
    RUN_TEST(test_stmt_close_sends_control_msgs);
    RUN_TEST(test_stmt_close_invalid_stmt_id);
    RUN_TEST(test_lob_streaming_null_stmt);
    RUN_TEST(test_lob_streaming_null_param_server_types);
    RUN_TEST(test_lob_streaming_null_param);
    RUN_TEST(test_execute_no_params_sends_id_and_exec);
    RUN_TEST(test_execute_with_retry_nonreadonly_skip);
    RUN_TEST(test_execute_with_params_int);
    RUN_TEST(test_execute_with_params_int64);
    RUN_TEST(test_execute_with_params_double);
    RUN_TEST(test_execute_with_params_string);
    RUN_TEST(test_execute_with_params_null);
    RUN_TEST(test_execute_with_params_bytes);
    RUN_TEST(test_execute_with_params_date);
    RUN_TEST(test_execute_with_params_decimal);
    RUN_TEST(test_execute_with_params_multiple);
    RUN_TEST(test_bind_decimal_success);
    RUN_TEST(test_bind_decimal_negative);
    RUN_TEST(test_bind_datetime_success);
    RUN_TEST(test_bind_interval_success);
    RUN_TEST(test_prepare_execute_null_stmt);
    RUN_TEST(test_prepare_execute_with_retry_null_stmt);
    RUN_TEST(test_prepare_execute_with_retry_null_conn);
    RUN_TEST(test_prepare_stmt_next_null_stmt);
    RUN_TEST(test_prepare_stmt_result_null_stmt);
    RUN_TEST(test_result_column_name_zero_count);
    RUN_TEST(test_result_column_type_zero_count);

    /* Phase 5 — transactions */
    RUN_TEST(test_begin_null_conn);
    RUN_TEST(test_begin_not_ready_conn);
    RUN_TEST(test_begin_already_in_transaction);
    RUN_TEST(test_begin_socket_not_connected);
    RUN_TEST(test_commit_null_conn);
    RUN_TEST(test_commit_no_active_transaction);
    RUN_TEST(test_rollback_null_conn);
    RUN_TEST(test_rollback_no_active_transaction);
    RUN_TEST(test_autocommit_null_conn);
    RUN_TEST(test_autocommit_default);
    RUN_TEST(test_autocommit_off_with_active_txn);
    RUN_TEST(test_isolation_null_conn);
    RUN_TEST(test_isolation_default);
    RUN_TEST(test_isolation_set_get);
    RUN_TEST(test_isolation_invalid);
    RUN_TEST(test_isolation_in_transaction);
    RUN_TEST(test_in_transaction_null);
    RUN_TEST(test_in_transaction_state);
    RUN_TEST(test_batch_begin_null_conn);
    RUN_TEST(test_batch_end_null_conn);
    RUN_TEST(test_batch_in_state_null);
    RUN_TEST(test_batch_begin_end_sends_opcodes);
    RUN_TEST(test_batch_begin_twice_invalid);
    RUN_TEST(test_batch_end_without_begin_invalid);
    RUN_TEST(test_batch_execute_null_params);
    RUN_TEST(test_batch_execute_not_ready_conn);
    RUN_TEST(test_batch_result_accessors_null_safe);
    RUN_TEST(test_savepoint_set_writes_opcode_payload_and_flag);
    RUN_TEST(test_savepoint_release_and_rollback_write_expected_opcodes);
    RUN_TEST(test_savepoint_rejected_in_autocommit);

    /* Phase 5 — sqlhosts */
    RUN_TEST(test_parse_null_output);
    RUN_TEST(test_parse_nonexistent_file);
    RUN_TEST(test_parse_env_sqlhosts);
    RUN_TEST(test_parse_and_find);
    RUN_TEST(test_parse_with_empty_lines_and_comments);
    RUN_TEST(test_find_null_entries);
    RUN_TEST(test_find_nonexistent_server);
    RUN_TEST(test_find_null_server_name);
    RUN_TEST(test_find_count_zero);

    /* Phase 7 — URI connection */
    RUN_TEST(test_uri_null_conn);
    RUN_TEST(test_uri_null_uri);
    RUN_TEST(test_uri_empty_uri);
    RUN_TEST(test_uri_bad_syntax);
    RUN_TEST(test_uri_unsupported_scheme);
    RUN_TEST(test_uri_missing_server_param);
    RUN_TEST(test_uri_onsoctcp_missing_host);
    RUN_TEST(test_uri_onsoctcp_full);
    RUN_TEST(test_uri_onsoctcp_no_creds);
    RUN_TEST(test_uri_onsoctcp_explicit_creds_override);
    RUN_TEST(test_uri_onsoctcp_default_db);
    RUN_TEST(test_uri_onsoctcp_url_encoded_creds);
    RUN_TEST(test_uri_onsocssl_full);
    RUN_TEST(test_uri_onsocssl_verify_peer_off);
    RUN_TEST(test_uri_onipcstr_full);
    RUN_TEST(test_uri_onipcstr_custom_socket);
    RUN_TEST(test_uri_onipcstr_default_socket_priority);
    RUN_TEST(test_uri_client_locale);
    RUN_TEST(test_uri_multiple_query_params);
    RUN_TEST(test_uri_user_only_no_password);
    RUN_TEST(test_uri_explicit_user_only);
    RUN_TEST(test_uri_explicit_password_only);
    RUN_TEST(test_uri_onsoctcp_missing_port);

    /* Phase 6 — integration tests */
    RUN_TEST(test_connect_success);
    RUN_TEST(test_connect_reject);
    RUN_TEST(test_connect_fragmented_conacc_body);
    RUN_TEST(test_connect_redirect);
    RUN_TEST(test_connect_bad_done);
    RUN_TEST(test_connect_tcp_fail);
    RUN_TEST(test_pool_create_acquire_release_destroy);
    RUN_TEST(test_pool_acquire_timeout_when_busy);
    RUN_TEST(test_pool_acquire_wakes_after_release);
    RUN_TEST(test_pool_reconnect_after_borrower_closed_connection);
    RUN_TEST(test_query_success_multi_row);
    RUN_TEST(test_query_success_ddl);
    RUN_TEST(test_query_error_response);
    RUN_TEST(test_query_null_params);
    RUN_TEST(test_txn_begin_success);
    RUN_TEST(test_txn_commit_success);
    RUN_TEST(test_txn_rollback_success);
    RUN_TEST(test_close_null_safe);
    RUN_TEST(test_close_ready_sends_exit);
    RUN_TEST(test_close_twice_safe);
    RUN_TEST(test_result_destroy_after_query);
    RUN_TEST(test_query_after_close);
#ifdef SQLI_ENABLE_LIVE_TESTS
    RUN_TEST(test_query_live_systables);
#endif

    return UNITY_END();
}
