/*
 * ifx_errmsg.h -- embedded IBM Informix error-message catalog
 *
 * Generated by gen_errmsg.c. Code universe (which error numbers exist)
 * comes from the IBM Informix JDBC driver's own bundled message
 * resources (com/informix/msg -- en_US properties files extracted
 * from the driver jar), restricted to the subsystems a SQL client can
 * actually surface as SQLException/SQLWarning text: sql, isam, sqli,
 * jdbc, jdbcminor, rds, os, sblob, security. Message TEXT comes from
 * the installed Informix server's own runtime catalog (.iem files)
 * where one exists, falling back to cerrmsg.txt, falling back to the
 * JDBC driver's own text only for jdbc/jdbcminor (no server-side
 * equivalent exists for those two bundles).
 *
 * 3412 distinct message codes, English (en_US) text only.
 *
 * Message text is stored in a compact tokenized form (a 383-entry
 * byte-pair-encoding-style dictionary of frequent substrings, 1 byte
 * per token for the 127 most frequent entries and 2 bytes for the
 * remaining 256) and must be expanded with ifx_errmsg_get() before
 * use -- do not read the raw bytes directly.
 *
 * A '%s', '%d', etc. placeholder appearing in an expanded message is
 * Informix's own substitution marker, NOT a C printf format string --
 * never pass an expanded message directly to printf()/snprintf() as
 * the format argument.
 *
 * Longest single expanded message in this catalog: 347 bytes
 * (excluding the terminating NUL).
 *
 * DO NOT EDIT ifx_errmsg_data.c BY HAND -- regenerate with gen_errmsg.
 */

#ifndef IFX_ERRMSG_H
#define IFX_ERRMSG_H

#include <stddef.h>
#include <stdint.h>

/*
 * Look up `code` (an Informix SQLCODE / ISAM error number, e.g. -206)
 * and write its expanded, NUL-terminated English message text into
 * `out` (a caller-supplied buffer of `outsz` bytes).
 *
 * Returns the number of bytes written excluding the NUL terminator on
 * success, or -1 if `code` is not in the catalog, or -2 if `outsz`
 * was too small to hold the full message (in which case `out` is
 * left unwritten -- call again with a larger buffer, e.g. sized from
 * IFX_ERRMSG_MAX_LEN).
 */
int ifx_errmsg_get(int32_t code, char *out, size_t outsz);

/* Upper bound, in bytes, on any single expanded message (excl. NUL). */
#define IFX_ERRMSG_MAX_LEN 347

#endif /* IFX_ERRMSG_H */
